/*++ 
 * linux/drivers/video/wmt/hw/wmt-vpp-reg.h
 * WonderMedia video post processor (VPP) driver
 *
 * Copyright c 2010  WonderMedia  Technologies, Inc.
 *
 * This program is free software: you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by 
 * the Free Software Foundation, either version 2 of the License, or 
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 * GNU General Public License for more details. 
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * WonderMedia Technologies, Inc.
 * 4F, 533, Chung-Cheng Road, Hsin-Tien, Taipei 231, R.O.C
--*/

/*
 * ChangeLog
 *
 * 2010-10-06  Sam Shen
 *     * create for wm8710 project
 */

/* Product ID: 8710 / Project ID: 3445 */

#ifndef WMT_DISP_REG_H
#define WMT_DISP_REG_H

#define WMT_FTBLK_DISP
#define WMT_FTBLK_DISP_HD
#define WMT_FTBLK_DISP_CSC

#define DISP_BASE2_ADDR 			DISP2_BASE_ADDR

#define REG_DISP_BASE1_BEGIN		(DISP_BASE_ADDR+0x00)
#define REG_DISP_CTRL				(DISP_BASE_ADDR+0x00)
#define REG_DISP_OPMOD				(DISP_BASE_ADDR+0x04)
#define REG_DISP_DACMOD				(DISP_BASE_ADDR+0x08)
#define REG_DISP_DACVAL				(DISP_BASE_ADDR+0x0C)
#define REG_DISP_FSCI_CFG			(DISP_BASE_ADDR+0x10)
#define REG_DISP_FSCI_VAL			(DISP_BASE_ADDR+0x14)
#define REG_DISP_FIL				(DISP_BASE_ADDR+0x18)
#define REG_DISP_AMP				(DISP_BASE_ADDR+0x1C)
#define REG_DISP_PSAMP				(DISP_BASE_ADDR+0x20)
#define REG_DISP_BRI				(DISP_BASE_ADDR+0x24)
#define REG_DISP_PEDESTAL			(DISP_BASE_ADDR+0x28)
#define REG_DISP_HSE				(DISP_BASE_ADDR+0x2C)
#define REG_DISP_YCDLY				(DISP_BASE_ADDR+0x30)
#define REG_DISP_HCOORD				(DISP_BASE_ADDR+0x34)
#define REG_DISP_TIMING				(DISP_BASE_ADDR+0x38)
#define REG_DISP_SYNC				(DISP_BASE_ADDR+0x3C)
#define REG_DISP_BURST1				(DISP_BASE_ADDR+0x40)
#define REG_DISP_BURST2				(DISP_BASE_ADDR+0x44)
#define REG_DISP_STATUS				(DISP_BASE_ADDR+0x48)
#define REG_DISP_EXTCFG1			(DISP_BASE_ADDR+0x4C)
#define REG_DISP_EXTCFG2			(DISP_BASE_ADDR+0x50)
#define REG_DISP_EXTCFG3			(DISP_BASE_ADDR+0x54)

#define REG_DISP_MV1				(DISP_BASE_ADDR+0x58)
#define REG_DISP_MV2				(DISP_BASE_ADDR+0x5C)
#define REG_DISP_MV3				(DISP_BASE_ADDR+0x60)
#define REG_DISP_MV4				(DISP_BASE_ADDR+0x64)
#define REG_DISP_MV5				(DISP_BASE_ADDR+0x68)
#define REG_DISP_MV6				(DISP_BASE_ADDR+0x6C)
#define REG_DISP_MV7				(DISP_BASE_ADDR+0x70)
#define REG_DISP_MV8				(DISP_BASE_ADDR+0x74)
#define REG_DISP_MVA1				(DISP_BASE_ADDR+0x78)
#define REG_DISP_MVA2				(DISP_BASE_ADDR+0x7C)
#define REG_DISP_MVA3				(DISP_BASE_ADDR+0x80)

#define REG_DISP_WSSC				(DISP_BASE_ADDR+0x84)
#define REG_DISP_WSSD				(DISP_BASE_ADDR+0x88)
#define REG_DISP_WSSFSCI			(DISP_BASE_ADDR+0x8C)

#define REG_DISP_CCC				(DISP_BASE_ADDR+0x90)
#define REG_DISP_CCDATA				(DISP_BASE_ADDR+0x94)

#define REG_DISP_VGA				(DISP_BASE_ADDR+0x98)
#define REG_DISP_DACTST				(DISP_BASE_ADDR+0x9C)

#define REG_DISP_P_AMP				(DISP_BASE_ADDR+0xA0)
#define REG_DISP_P_YLVL				(DISP_BASE_ADDR+0xA4)
#define REG_DISP_P_YCDLY			(DISP_BASE_ADDR+0xA8)
#define REG_DISP_P_SYNC				(DISP_BASE_ADDR+0xAC)
#define REG_DISP_P_MV1				(DISP_BASE_ADDR+0xB0)
#define REG_DISP_P_MV2				(DISP_BASE_ADDR+0xB4)
#define REG_DISP_P_MV3				(DISP_BASE_ADDR+0xB8)
#define REG_DISP_P_MV4				(DISP_BASE_ADDR+0xBC)
#define REG_DISP_P_MV5				(DISP_BASE_ADDR+0xC0)
#define REG_DISP_P_MVA1				(DISP_BASE_ADDR+0xC4)
#define REG_DISP_P_MVA2				(DISP_BASE_ADDR+0xC8)
#define REG_DISP_P_WSSC				(DISP_BASE_ADDR+0xCC)
#define REG_DISP_P_WSSD				(DISP_BASE_ADDR+0xD0)
#define REG_DISP_P_WSSFSCI			(DISP_BASE_ADDR+0xD4)

#define REG_DISP_DACD_DCVAL			(DISP_BASE_ADDR+0xD8)
#define REG_DISP_DACE_DCVAL			(DISP_BASE_ADDR+0xDC)
#define REG_DISP_DACF_DCVAL			(DISP_BASE_ADDR+0xE0)
#define REG_DISP_DAC_DEBUG1			(DISP_BASE_ADDR+0xE4)

#define REG_DISP_EXT_TIMING1		(DISP_BASE_ADDR+0xF0)
#define REG_DISP_EXT_TIMING2		(DISP_BASE_ADDR+0xF4)
#define REG_DISP_P_TIMING			(DISP_BASE_ADDR+0xF8)
#define REG_DISP_INV_TVCLK			(DISP_BASE_ADDR+0xFC)

#define REG_DISP_BASE1_END			(DISP_BASE_ADDR+0xFC)

// DISP Base2
#define REG_DISP_BASE2_BEGIN		(DISP_BASE2_ADDR+0x00)
#define REG_DISP_FILTER1			(DISP_BASE2_ADDR+0x00)
#define REG_DISP_FILTER2			(DISP_BASE2_ADDR+0x04)
#define REG_DISP_FILTER3			(DISP_BASE2_ADDR+0x08)
#define REG_DISP_FILTER4			(DISP_BASE2_ADDR+0x0C)
#define REG_DISP_FILTER5			(DISP_BASE2_ADDR+0x10)
#define REG_DISP_FILTER6			(DISP_BASE2_ADDR+0x14)
#define REG_DISP_FILTER7			(DISP_BASE2_ADDR+0x18)
#define REG_DISP_FILTER8			(DISP_BASE2_ADDR+0x1C)

#define REG_DISP_CSC1				(DISP_BASE2_ADDR+0x20)
#define REG_DISP_CSC2				(DISP_BASE2_ADDR+0x24)
#define REG_DISP_CSC3				(DISP_BASE2_ADDR+0x28)
#define REG_DISP_CSC4				(DISP_BASE2_ADDR+0x2C)
#define REG_DISP_CSC5				(DISP_BASE2_ADDR+0x30)
#define REG_DISP_CSC6				(DISP_BASE2_ADDR+0x34)
#define REG_DISP_CSC7				(DISP_BASE2_ADDR+0x38)
#define REG_DISP_CSC				(DISP_BASE2_ADDR+0x3C)

#define REG_DISP_HD_CTL				(DISP_BASE2_ADDR+0x40)
#define REG_DISP_HD_FRAME_TOTAL		(DISP_BASE2_ADDR+0x44)
#define REG_DISP_CSC_ENABLE			(DISP_BASE2_ADDR+0x48)
#define REG_DISP_HSYNC_TMR			(DISP_BASE2_ADDR+0x4C)
#define REG_DISP_VBIS_TMR			(DISP_BASE2_ADDR+0x50)
#define REG_DISP_1080I_1T			(DISP_BASE2_ADDR+0x54)
#define REG_DISP_BASE2_END			(DISP_BASE2_ADDR+0x54)

// REG_DISP_CTRL,0x00
#define DISP_VGA_VSYNC_POLAR		REG_DISP_CTRL,BIT17,17
#define DISP_VGA_HSYNC_POLAR		REG_DISP_CTRL,BIT16,16
#define DISP_INPUT_FIELD			REG_DISP_CTRL,BIT12,12
#define DISP_SW_SHIFT				REG_DISP_CTRL,BIT10,10
#define DISP_SHIFT_TYPE				REG_DISP_CTRL,0x300,8
#define DISP_P_MODE_ONLY			REG_DISP_CTRL,BIT7,7
#define DISP_I_MODE_ONLY			REG_DISP_CTRL,BIT6,6
#define DISP_BT470					REG_DISP_CTRL,BIT5,5
#define DISP_DEBUG_MODE 			REG_DISP_CTRL,BIT4,4
#define DISP_FIELD_POLAR			REG_DISP_CTRL,BIT3,3
#define DISP_HRST_FSCI				REG_DISP_CTRL,BIT2,2
#define DISP_EXTTV_EN				REG_DISP_CTRL,BIT1,1
#define DISP_EN						REG_DISP_CTRL,BIT0,0

// REG_DISP_OPMOD,0x04
#define DISP_CLAMP_EN				REG_DISP_OPMOD,BIT8,8
#define DISP_PAL_NC_MODE			REG_DISP_OPMOD,BIT7,7
#define DISP_PAL_N_MODE				REG_DISP_OPMOD,BIT6,6
#define DISP_EXT_SYNC_SEL			REG_DISP_OPMOD,0x30,4
#define DISP_LINE_SEL_525			REG_DISP_OPMOD,BIT3,3
#define DISP_TVSYS_NTSC				REG_DISP_OPMOD,BIT2,2
#define DISP_COLORBAR_EN			REG_DISP_OPMOD,BIT1,1
#define DISP_DOT_CRAWL				REG_DISP_OPMOD,BIT0,0

// REG_DISP_DACMOD,0x08
#define DISP_DAC_HPS				REG_DISP_DACMOD,0x1C00000,22
#define DISP_DAC_RESET				REG_DISP_DACMOD,0x70000,16
#define DISP_DAC_A_2X				REG_DISP_DACMOD,BIT13,13
#define DISP_DAC_BCD_2X				REG_DISP_DACMOD,BIT12,12
#define DISP_DAC_SEL				REG_DISP_DACMOD,0xE00,9
#define DISP_DAC_MANUAL_SENSE		REG_DISP_DACMOD,BIT8,8
#define DISP_DAC_AUTO_SENSE			REG_DISP_DACMOD,BIT7,7
#define DISP_DAC_A_PWRDN			REG_DISP_DACMOD,BIT6,6
#define DISP_DAC_B_PWRDN			REG_DISP_DACMOD,BIT3,3
#define DISP_DAC_C_PWRDN			REG_DISP_DACMOD,BIT2,2
#define DISP_DAC_D_PWRDN			REG_DISP_DACMOD,BIT1,1
#define DISP_DAC_SENSE_EN			REG_DISP_DACMOD,BIT0,0

// REG_DISP_DACVAL,0x0C
#define DISP_DAC_LOWPWR_VAL			REG_DISP_DACVAL,0x3FF0000,16
#define DISP_DAC_NORMAL_VAL			REG_DISP_DACVAL,0x3FF,0

// REG_DISP_FSCI_CFG,0x10
#define DISP_FSCI_PHASE_ADJ			REG_DISP_FSCI_CFG,0x7FF,0

// REG_DISP_FSCI_VAL,0x14

// REG_DISP_FIL,0x18
#define DISP_FIL_C_BYPASS			REG_DISP_FIL,BIT7,7
#define DISP_FIL_LUMA_ADJUST		REG_DISP_FIL,0x70,4
#define DISP_FIL_Y_BYPASS			REG_DISP_FIL,BIT0,0

// REG_DISP_AMP,0x1C
#define DISP_SYNC_R_PR				REG_DISP_AMP,BIT26,26
#define DISP_SYNC_G					REG_DISP_AMP,BIT25,25
#define DISP_SYNC_B_PB				REG_DISP_AMP,BIT24,24
#define DISP_SYNC_Y_CONTRAST		REG_DISP_AMP,0xFF0000,16
#define DISP_SYNC_U_SATURATION		REG_DISP_AMP,0xFF00,8
#define DISP_SYNC_V_SATURATION		REG_DISP_AMP,0xFF,0

// REG_DISP_PSAMP,0x20
#define DISP_PYGAF					REG_DISP_PSAMP,0xFF0000,16
#define DISP_PBGAF					REG_DISP_PSAMP,0xFF00,8
#define DISP_PRGAF					REG_DISP_PSAMP,0xFF,0

// REG_DISP_BRI,0x24
#define DISP_BLACK_LEVEL			REG_DISP_BRI,0xFF,0

// REG_DISP_PEDESTAL,0x28
#define DISP_BLANK_2LEVEL			REG_DISP_PEDESTAL,0xFF0000,16
#define DISP_BLANK_LEVEL			REG_DISP_PEDESTAL,0xFF,0

// REG_DISP_HSE,0x2C
#define DISP_HUE_ADJUST				REG_DISP_HSE,0x7FF,0

// REG_DISP_YCDLY,0x30
#define DISP_V_DELAY				REG_DISP_YCDLY,0x1C0,6
#define DISP_U_DELAY				REG_DISP_YCDLY,0x38,3
#define DISP_Y_DELAY				REG_DISP_YCDLY,0x7,0

// REG_DISP_HCOORD,0x34
#define DISP_TG_TOTAL_PIXEL			REG_DISP_HCOORD,0xFFF,0

// REG_DISP_TIMING,0x38
#define DISP_TG_H_START				REG_DISP_TIMING,0x3000000,24
#define DISP_TG_H_END				REG_DISP_TIMING,0x3FFE00,9
#define DISP_TG_H_STA				REG_DISP_TIMING,0x1FF,0

// REG_DISP_SYNC,0x3C
#define DISP_SYNC_STEP				REG_DISP_SYNC,0x1FF00,8
#define DISP_SYNC_WIDTH				REG_DISP_SYNC,0xFF,0

// REG_DISP_BURST1,0x40
#define DISP_BURST_STEP				REG_DISP_BURST1,0x3FE0000,17
#define DISP_BURST_END				REG_DISP_BURST1,0x1FF00,8
#define DISP_BURST_STA				REG_DISP_BURST1,0xFF,0

// REG_DISP_BURST2,0x44
#define DISP_BURST_AMP				REG_DISP_BURST2,0x1FF,0

// REG_DISP_STATUS,0x48
#define DISP_ECD_FIELD				REG_DISP_STATUS,BIT8,8
#define DISP_MV_ENABLE				REG_DISP_STATUS,BIT7,7
#define DISP_DAC_A_CONNECT			REG_DISP_STATUS,BIT6,6
#define DISP_DAC_B_CONNECT			REG_DISP_STATUS,BIT3,3
#define DISP_DAC_C_CONNECT			REG_DISP_STATUS,BIT2,2
#define DISP_DAC_D_CONNECT			REG_DISP_STATUS,BIT1,1
#define DISP_FIFO_UNDERRUN			REG_DISP_STATUS,BIT0,0

// REG_DISP_EXTCFG1,0x4C
#define DISP_TG_FIELD_DIFF			REG_DISP_EXTCFG1,BIT31,31
#define DISP_TG_V_DIFF				REG_DISP_EXTCFG1,0x7FE00000,21
#define DISP_TG_H_DIFF				REG_DISP_EXTCFG1,0x1FFC00,10
#define DISP_TG_TOTAL_LINE			REG_DISP_EXTCFG1,0x3FF,0

// REG_DISP_EXTCFG2,0x50
#define DISP_TG_VBIE				REG_DISP_EXTCFG2,0xFE000000,25
#define DISP_TG_PVBI				REG_DISP_EXTCFG2,0x1F00000,20
#define DISP_TG_F2_END				REG_DISP_EXTCFG2,0xFFC00,10
#define DISP_TG_F1_END				REG_DISP_EXTCFG2,0x3FF,0

// REG_DISP_EXTCFG3,0x54
#define DISP_TG_F2_TOTAL_LINE		REG_DISP_EXTCFG3,0xFFC00000,22
#define DISP_TG_F2_BEG				REG_DISP_EXTCFG3,0x3F0000,16
#define DISP_TG_F1_TOTAL_LINE		REG_DISP_EXTCFG3,0xFFC0,6
#define DISP_TG_F1_BEG				REG_DISP_EXTCFG3,0x3F,0

/*----------------------- DISP MV --------------------------------------*/
// REG_DISP_MV1,0x58
#define DISP_MV_EN					REG_DISP_MV1,BIT30,30
#define DISP_MV_N4					REG_DISP_MV1,0x3F000000,24
#define DISP_MV_N3					REG_DISP_MV1,0xFC0000,18
#define DISP_MV_N2					REG_DISP_MV1,0x3F000,12
#define DISP_MV_N1					REG_DISP_MV1,0xFC0,6
#define DISP_MV_PS_AGC_EN			REG_DISP_MV1,BIT5,5
#define DISP_MV_BP_EN				REG_DISP_MV1,BIT4,4
#define DISP_MV_CS_EN				REG_DISP_MV1,BIT3,3
#define DISP_MV_CYCLIC_EN			REG_DISP_MV1,BIT2,2
#define DISP_MV_OUT_VBI				REG_DISP_MV1,BIT1,1
#define DISP_MV_IN_VBI				REG_DISP_MV1,BIT0,0

// REG_DISP_MV2,0x5C
#define DISP_MV_N8B_S				REG_DISP_MV2,0xFF0000,16
#define DISP_MV_N8A_S				REG_DISP_MV2,0xFF00,8
#define DISP_MV_N7					REG_DISP_MV2,0xC0,6
#define DISP_MV_N6					REG_DISP_MV2,0x38,3
#define DISP_MV_N5					REG_DISP_MV2,0x7,0

// REG_DISP_MV3,0x60
#define DISP_MV_N9B_S				REG_DISP_MV3,0xFFC00,10
#define DISP_MV_N9A_S				REG_DISP_MV3,0x3FF,0

// REG_DISP_MV4,0x64
#define DISP_MV_N10B_S				REG_DISP_MV4,0xFFC00,10
#define DISP_MV_N10A_S				REG_DISP_MV4,0x3FF,0

// REG_DISP_MV5,0x68
#define DISP_MV_N12					REG_DISP_MV5,0x3FFF8000,15
#define DISP_MV_N11					REG_DISP_MV5,0x7FFF,0

// REG_DISP_MV6,0x6C
#define DISP_MV_N16					REG_DISP_MV6,BIT24,24
#define DISP_MV_N15					REG_DISP_MV6,0xFF0000,16
#define DISP_MV_N14					REG_DISP_MV6,0xFF00,8
#define DISP_MV_N13					REG_DISP_MV6,0xFF,0

// REG_DISP_MV7,0x70
#define DISP_MV_N20					REG_DISP_MV7,0x3000000,24
#define DISP_MV_N19S				REG_DISP_MV7,0xFF0000,16
#define DISP_MV_N18S				REG_DISP_MV7,0xFF00,8
#define DISP_MV_N17S				REG_DISP_MV7,0xFF,0

// REG_DISP_MV8,0x74
#define DISP_MV_N22					REG_DISP_MV8,BIT10,10
#define DISP_MV_N21					REG_DISP_MV8,0x3FF,0

// REG_DISP_MVA1,0x78
#define DISP_MV_REDUCE_BLANK_AMP	REG_DISP_MVA1,0xFF800000,23
#define DISP_MV_BP_WIDTH			REG_DISP_MVA1,0x7F0000,16
#define DISP_MV_BP_AMP				REG_DISP_MVA1,0xFF00,8
#define DISP_MV_AGC_WIDTH			REG_DISP_MVA1,0xFF,0

// REG_DISP_MVA2,0x7C
#define DISP_MV_PULSE_HI			REG_DISP_MVA2,0xFF000000,24
#define DISP_MV_PULSE_LO			REG_DISP_MVA2,0xFF0000,16
#define DISP_MV_MAX_AMP				REG_DISP_MVA2,0xFF00,8
#define DISP_MV_AGC_CYCLIC			REG_DISP_MVA2,0xFF,0

// REG_DISP_MVA3,0x80
#define DISP_MV_ADV_END				REG_DISP_MVA3,0xFFF000,12
#define DISP_MV_ADV_STA				REG_DISP_MVA3,0xFFF,0

/*----------------------- DISP WSS --------------------------------------*/
// REG_DISP_WSSC,0x84
#define DISP_WSS_AMP				REG_DISP_WSSC,0xFF000,12
#define DISP_WSS_STA				REG_DISP_WSSC,0xFFC,2
#define DISP_WSS_F2_EN				REG_DISP_WSSC,BIT1,1
#define DISP_WSS_F1_EN				REG_DISP_WSSC,BIT0,0

// REG_DISP_WSSD,0x88
#define DISP_WSS_DATA				REG_DISP_WSSD,0xFFFFF,0

// REG_DISP_WSSFSCI,0x8C
#define DISP_WSS_FSCI				REG_DISP_WSSFSCI,0xFFFFF,0

/*----------------------- DISP CC --------------------------------------*/
// REG_DISP_CCC,0x90
#define DISP_CC_START				REG_DISP_CCC,0x1FF80000,19
#define DISP_CC_ENCODE				REG_DISP_CCC,BIT18,18
#define DISP_CC_F2_EN				REG_DISP_CCC,BIT17,17
#define DISP_CC_F1_EN				REG_DISP_CCC,BIT16,16
#define DISP_CC_SLOPE				REG_DISP_CCC,0xFF00,8
#define DISP_CC_AMP					REG_DISP_CCC,0xFF,0

// REG_DISP_CCDATA,0x94
#define DISP_CC_F2_BYTE2			REG_DISP_CCDATA,0xFF000000,24
#define DISP_CC_F2_BYTE1			REG_DISP_CCDATA,0xFF0000,16
#define DISP_CC_F1_BYTE2			REG_DISP_CCDATA,0xFF00,8
#define DISP_CC_F1_BYTE1			REG_DISP_CCDATA,0xFF,0

/*----------------------- DISP VGA --------------------------------------*/
// REG_DISP_VGA,0x98
#define DISP_VGA_VSYNC				REG_DISP_VGA,0x7FFF0000,16
#define DISP_VGA_HSYNC				REG_DISP_VGA,0x7FFF,0

// REG_DISP_DACTST,0x9C
#define DISP_DAC_DCMODE				REG_DISP_DACTST,0xFC000000,26
#define DISP_DAC_VDMUX				REG_DISP_DACTST,0x700000,20
#define DISP_DAC_TEST_EN			REG_DISP_DACTST,BIT19,19
#define DISP_DAC_DC_TEST_MODE		REG_DISP_DACTST,BIT18,18
#define DISP_DAC_AC_TEST_MODE		REG_DISP_DACTST,0x30000,16
#define DISP_DAC_DC_VAL				REG_DISP_DACTST,0x3FF,0

/*----------------------- DISP Progressive --------------------------------------*/
// REG_DISP_P_AMP,0xA0
#define DISP_P_SYNC_R_PR			REG_DISP_P_AMP,BIT26,26
#define DISP_P_SYNC_G				REG_DISP_P_AMP,BIT25,25
#define DISP_P_SYNC_B_PB			REG_DISP_P_AMP,BIT24,24
#define DISP_P_PYGAF				REG_DISP_P_AMP,0xFF0000,16
#define DISP_P_PBBAF				REG_DISP_P_AMP,0xFF00,8
#define DISP_P_PRRAF				REG_DISP_P_AMP,0xFF,0

// REG_DISP_P_YLVL,0xA4
#define DISP_P_BLACK_LEVEL			REG_DISP_P_YLVL,0xFF000000,24
#define DISP_P_BLANK_LEVEL2			REG_DISP_P_YLVL,0x3FE00,9
#define DISP_P_BLANK_LEVEL			REG_DISP_P_YLVL,0x1FF,0

// REG_DISP_P_YCDLY,0xA8
#define DISP_P_SW_VBI_EN			REG_DISP_P_YCDLY,BIT13,13

// REG_DISP_P_SYNC,0xAC
#define DISP_P_SYNC_STEP			REG_DISP_P_SYNC,0x1FF00,8
#define DISP_P_SYNC_WIDTH			REG_DISP_P_SYNC,0xFF,0

/*----------------------- DISP Macrovision (Progressive) --------------------------------------*/
// REG_DISP_P_MV1,0xB0
#define DISP_P_MV_EN				REG_DISP_P_MV1,BIT30,30
#define DISP_P_MV_N8B_S				REG_DISP_P_MV1,0x3FC000,14
#define DISP_P_MV_N8A_S				REG_DISP_P_MV1,0x3FC0,6
#define DISP_P_MV_PS_AGC_EN			REG_DISP_P_MV1,BIT5,5
#define DISP_P_MV_BP_EN				REG_DISP_P_MV1,BIT4,4
#define DISP_P_MV_CS_EN				REG_DISP_P_MV1,BIT3,3
#define DISP_P_MV_CYCLIC_EN			REG_DISP_P_MV1,BIT2,2
#define DISP_P_MV_OUT_VBI			REG_DISP_P_MV1,BIT1,1
#define DISP_P_MV_IN_VBI			REG_DISP_P_MV1,BIT0,0

// REG_DISP_P_MV2,0xB4
#define DISP_P_MV_N9B_S				REG_DISP_P_MV2,0xFFC00,10
#define DISP_P_MV_N9A_S				REG_DISP_P_MV2,0x3FF,0

// REG_DISP_P_MV3,0xB8
#define DISP_P_MV_N10B_S			REG_DISP_P_MV3,0xFFC00,10
#define DISP_P_MV_N10A_S			REG_DISP_P_MV3,0x3FF,0

// REG_DISP_P_MV4,0xBC
#define DISP_P_MV_N12				REG_DISP_P_MV4,0x3FFF8000,15
#define DISP_P_MV_N11				REG_DISP_P_MV4,0x7FFF,0

// REG_DISP_P_MV5,0xC0
#define DISP_P_N22					REG_DISP_P_MV5,BIT24,24
#define DISP_P_N15					REG_DISP_P_MV5,0xFF0000,16
#define DISP_P_N14					REG_DISP_P_MV5,0xFF00,8
#define DISP_P_N13					REG_DISP_P_MV5,0xFF,0

// REG_DISP_P_MVA1,0xC4
#define DISP_P_BL_REDUCE			REG_DISP_P_MVA1,0xFF800000,23
#define DISP_P_BP_WIDTH				REG_DISP_P_MVA1,0x7F0000,16
#define DISP_P_BP_AMP				REG_DISP_P_MVA1,0xFF00,8
#define DISP_P_AGC_WIDTH			REG_DISP_P_MVA1,0xFF,0

// REG_DISP_P_MVA2,0xC8
#define DISP_P_PULSE_HI				REG_DISP_P_MVA2,0xFF000000,24
#define DISP_P_PULSE_LO				REG_DISP_P_MVA2,0xFF0000,16
#define DISP_P_MAX_AMP				REG_DISP_P_MVA2,0xFF00,8
#define DISP_P_STEP					REG_DISP_P_MVA2,0xFF,0

/*----------------------- DISP WSS (Progressive) --------------------------------------*/
// REG_DISP_P_WSSC,0xCC
#define DISP_P_WSS_AMP				REG_DISP_P_WSSC,0xFF000,12
#define DISP_P_WSS_START			REG_DISP_P_WSSC,0xFFC,2
#define DISP_P_WSS_F2_EN			REG_DISP_P_WSSC,BIT1,1
#define DISP_P_WSS_F1_EN			REG_DISP_P_WSSC,BIT0,0

// REG_DISP_P_WSSD,0xD0
#define DISP_P_WSS_DATA				REG_DISP_P_WSSD,0xFFFFF,0

// REG_DISP_P_WSSFSCI,0xD4
#define DISP_P_WSS_FSCI				REG_DISP_P_WSSFSCI,0xFFFFF,0

/*----------------------- DISP DAC --------------------------------------*/
// REG_DISP_DACD_DCVAL,0xD8
#define DISP_DAC_D_VAL				REG_DISP_DACD_DCVAL,0x3FF,0

// REG_DISP_DACE_DCVAL,0xDC
#define DISP_DAC_E_VAL				REG_DISP_DACE_DCVAL,0x3FF,0

// REG_DISP_DACF_DCVAL,0xE0
#define DISP_DAC_F_VAL				REG_DISP_DACF_DCVAL,0x3FF,0

// REG_DISP_DAC_DEBUG1,0xE4
#define DISP_DAC_OUT_CURRENT		REG_DISP_DAC_DEBUG1,0x700,8
#define DISP_RD1ENC					REG_DISP_DAC_DEBUG1,BIT1,1
#define DISP_RD0ENC					REG_DISP_DAC_DEBUG1,BIT0,0

/*----------------------- DISP EXTTV TG --------------------------------------*/
// REG_DISP_EXT_TIMING1,0xF0
#define DISP_EXT_TG_END				REG_DISP_EXT_TIMING1,0x3FFE00,9
#define DISP_EXT_TG_STA				REG_DISP_EXT_TIMING1,0x1FF,0

// REG_DISP_EXT_TIMING2,0xF4
#define DISP_EXT_F_DIFF				REG_DISP_EXT_TIMING2,BIT21,21
#define DISP_EXT_V_DIFF				REG_DISP_EXT_TIMING2,0x1FF800,11
#define DISP_EXT_H_DIFF				REG_DISP_EXT_TIMING2,0x7FF,0

// REG_DISP_P_TIMING,0xF8
#define DISP_P_SW_VBIEND			REG_DISP_P_TIMING,BIT20,20
#define DISP_P_F1_END				REG_DISP_P_TIMING,0x3FF00,8
#define DISP_P_F1_BEG				REG_DISP_P_TIMING,0xFF,0

// REG_DISP_INV_TVCLK,0xFC
#define DISP_CCIR_NVTVCLK_EN		REG_DISP_INV_TVCLK,BIT1,1
#define DISP_DAC_NVTVCLK_EN			REG_DISP_INV_TVCLK,BIT0,0

// DISP BASE 2
// REG_DISP_CSC,0x3C
#define DISP_YSUB_16_EN				REG_DISP_CSC,BIT1,1
#define DISP_CSC_MODE				REG_DISP_CSC,BIT0,0

// REG_DISP_HD_CTL,0x40
#define DISP_PR_OUT_MODE			REG_DISP_HD_CTL,0x30,4
#define DISP_IT_OUT_MODE			REG_DISP_HD_CTL,0xC,2
#define DISP_HDTV_IN				REG_DISP_HD_CTL,BIT1,1
#define DISP_HDTV_EN				REG_DISP_HD_CTL,BIT0,0

// REG_DISP_HD_FRAME_TOTAL,0x44
#define DISP_FRAME_TOTAL_HD			REG_DISP_HD_FRAME_TOTAL,BIT0,0	// V total

// REG_DISP_CSC_ENABLE,0x48
#define DISP_INTERLACE_CSC_EN		REG_DISP_CSC_ENABLE,BIT1,1
#define DISP_PROGRESS_CSC_EN		REG_DISP_CSC_ENABLE,BIT0,0

// REG_DISP_HSYNC_TMR,0x4C
#define DISP_GOVR_F_DIFF			REG_DISP_HSYNC_TMR,BIT26,26
#define DISP_GOVR_V_DIFF			REG_DISP_HSYNC_TMR,0x3FF0000,16
#define DISP_GOVR_H_DIFF			REG_DISP_HSYNC_TMR,0x7FF,0

// REG_DISP_VBIS_TMR,0x50
#define DISP_VBIE_V_DIFF			REG_DISP_VBIS_TMR,0x7F,0

// REG_DISP_1080I_1T,0x54
#define DISP_1080I_1T				REG_DISP_1080I_1T,BIT0,0

#endif				/* WMT_DISP_REG_H */
