#
# Makefile for the Sensor driver
#

# Each configuration option enables a list of files.

obj-$(CONFIG_WMT_SENSOR_MMA7660) += mma7660_gsensor/

obj-$(CONFIG_WMT_SENSOR_KXTE9) += kxte9_gsensor/
