#
# Makefile for the Wonder Media silicon image 9024 HDMI driver
#
g_sil9024-objs                := TPI.o HDCP.o TPI_Access.o EDID.o i2c_master_sw.o AV_Config.o Globals.o VideoModeTable.o wmt_sil9024.o
obj-$(CONFIG_HDCP_SIL902X_WMT) += g_sil9024.o
