#
## Makefile for ALSA WMT
#
#
# WMT SOC Support
snd-soc-wmt-i2s-objs := wmt-i2s.o wmt_swmixer.o
snd-soc-wmt-objs := wmt-soc.o wmt-pcm.o

obj-$(CONFIG_SND_WMT_SOC_I2S) += snd-soc-wmt-i2s.o
obj-$(CONFIG_SND_WMT_SOC) += snd-soc-wmt.o